def uttt_tutorial():
    """
    Asks the user if they would like to run the tutorial.
    :return: Prints tutorial if the player wants. Otherwise, does nothing.
    """
    tutorial = str(input("Would you like a brief tutorial, Y/N? ")).upper()
    while tutorial != "Y" and tutorial != "N":
        tutorial = str(input("Please enter Y/N for a tutorial: ")).upper()
    if tutorial == "Y":
        print(
            "\nWelcome to the Ultimate Tic Tac Toe tutorial!\n"
            "If you prefer visual learning, please refer to the linked video in the README.\n"
            "Here are the rules: \n\n"
            "The global Tic Tac Toe board is comprised of 9 local Tic Tac Toe boards.\n"
            "These global boards are labeled A-I, and contain the numbers 1-9:\n\n"
            "       ||       ||             1 | 2 | 3  ||  1 | 2 | 3  ||  1 | 2 | 3\n"
            "       ||       ||            ----------- || ----------- || -----------\n"
            "   A   ||   B   ||   C         4 | 5 | 6  ||  4 | 5 | 6  ||  4 | 5 | 6\n"
            "       ||       ||            ----------- || ----------- || -----------\n"
            "       ||       ||             7 | 8 | 9  ||  7 | 8 | 9  ||  7 | 8 | 9\n"
            "========================     ===========================================\n"
            "       ||       ||             1 | 2 | 3  ||  1 | 2 | 3  ||  1 | 2 | 3\n"
            "       ||       ||            ----------- || ----------- || -----------\n"
            "   D   ||   E   ||   F         4 | 5 | 6  ||  4 | 5 | 6  ||  4 | 5 | 6\n"
            "       ||       ||            ----------- || ----------- || -----------\n"
            "       ||       ||             7 | 8 | 9  ||  7 | 8 | 9  ||  7 | 8 | 9\n"
            "========================     ===========================================\n"
            "       ||       ||             1 | 2 | 3  ||  1 | 2 | 3  ||  1 | 2 | 3\n"
            "       ||       ||            ----------- || ----------- || -----------\n"
            "   G   ||   H   ||   I         4 | 5 | 6  ||  4 | 5 | 6  ||  4 | 5 | 6\n"
            "       ||       ||            ----------- || ----------- || -----------\n"
            "       ||       ||             7 | 8 | 9  ||  7 | 8 | 9  ||  7 | 8 | 9\n\n"
            "The game begins by randomly picking the player that will choose to be X or O. "
            "Whoever begins with X has the first move.\n"
            "The first player begins by choosing which game A-I they will make their first move in.\n"
            "Once the game is chosen, the player will input the space number they wish to occupy.\n"
            "The chosen position in the local game sends the next player to choose in the relative global location.\n\n"
            "Example:\n"
            "If the first player were to choose A9, the board would then look like:\n\n"
            "    |   |    ||    |   |    ||    |   |  \n"
            " ----------- || ----------- || -----------\n"
            "    |   |    ||    |   |    ||    |   |  \n"
            " ----------- || ----------- || -----------\n"
            "    |   | X  ||    |   |    ||    |   |  \n"
            "===========================================\n"
            "    |   |    ||    |   |    ||    |   |  \n"
            " ----------- || ----------- || -----------\n"
            "    |   |    ||    |   |    ||    |   |  \n"
            " ----------- || ----------- || -----------\n"
            "    |   |    ||    |   |    ||    |   |  \n"
            "===========================================\n"
            "    |   |    ||    |   |    ||    |   |  \n"
            " ----------- || ----------- || -----------\n"
            "    |   |    ||    |   |    ||    |   |  \n"
            " ----------- || ----------- || -----------\n"
            "    |   |    ||    |   |    ||    |   |  \n\n"
            "Because of the relative position(bottom-right), the second player would then choose from game I\n"
            "If they were to choose I1, the first player would be sent to game A and the board would look like:\n\n"
            "    |   |    ||    |   |    ||    |   |  \n"
            " ----------- || ----------- || -----------\n"
            "    |   |    ||    |   |    ||    |   |  \n"
            " ----------- || ----------- || -----------\n"
            "    |   | X  ||    |   |    ||    |   |  \n"
            "===========================================\n"
            "    |   |    ||    |   |    ||    |   |  \n"
            " ----------- || ----------- || -----------\n"
            "    |   |    ||    |   |    ||    |   |  \n"
            " ----------- || ----------- || -----------\n"
            "    |   |    ||    |   |    ||    |   |  \n"
            "===========================================\n"
            "    |   |    ||    |   |    ||  O |   |  \n"
            " ----------- || ----------- || -----------\n"
            "    |   |    ||    |   |    ||    |   |  \n"
            " ----------- || ----------- || -----------\n"
            "    |   |    ||    |   |    ||    |   |  \n\n"
            "If a player wins a local game, the entire local game is marked as a victory for that player.\n"
            "Once the outcome of a local game is decided(win, lose, or draw), no more moves can be made in that game.\n"
            "If a player is sent to a board that has reached that point, they may choose to move wherever they please.\n"
            "The game has two conclusions:\n"
            "   -A player wins a string of local games such that they win the global board\n"
            "   -No player wins and the game results in draw\n"
        )